name: demo Akey SDK and Dynamic Secrets

on:
  workflow_dispatch:
    ##############################
    # inputs var
    #############################
    inputs:
      aws_region:
        description: 'AWS default region'
        type: string
        required: true
        default: us-east-1
      akey_host:
        description: 'Main Akey host'
        type: string
        required: true
        default: "https://api.akeyless.io"
      
      akey_gateway:
          description: 'Main Akey gateway'
          type: string
          required: true
          default: "https://13.57.245.231.nip.io"
      db_host:
          description: 'db host name'
          type: string
          required: true
          default: "54.241.82.232"

      db_name:
          description: 'Database name'
          type: string
          required: true
          default: "akey_database"

      db_table:
          description: 'Table name'
          type: string
          required: true
          default: "user_info"
          
######################
# Jobs
######################

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pwd
          ls -la ./
          pip install -r ../Task4/sdk/requirements.txt                       
          
      - name: execute py script # run main.py
        env:
          access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
          access-key: ${{ secrets.AKEYLESS_ACCESS_KEY }}
          akey_host: ${{ inputs.akey_host }}
          akey_gateway: ${{ inputs.akey_gateway }}
          db_host: os.environ['db_host']
          db_name: os.environ['db_name']
          db_table: os.environ['db_table']

        run: python3 Task4/sdk/get_ds.py




  

  