
on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: 'AWS default region'
        type: string
        required: true
        default: us-east-1

######################
# Jobs
######################
jobs:

  sql_dynamic_secrets:
    runs-on: ubuntu-latest
    name: SQL dynamic secrets (default)
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      #uses: actions/checkout@v2
      uses: LanceMcCarthy/akeyless-action@v3.5.0
      with:
        fetch-depth: 0


    - name: Fetch dynamic secrets from Akleyless
      id: fetch-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        access-key: ${{ secrets.AKEYLESS_ACCESS_KEY }}
        access-type: access_key
        dynamic-secrets: '{"/mySQLds-1": "my_dynamic_secret"}'


    - name: Verify Job Outputs using jq
      run: |
        echo "Your job output secret is ${{ steps.fetch-secrets.outputs.my_dynamic_secret }}"
        echo "Manually parsed ID:" 
        echo '${{ steps.fetch-secrets.outputs.my_dynamic_secret }}' | jq '.id'
        echo "Manually parsed USER:" 
        echo '${{ steps.fetch-secrets.outputs.my_dynamic_secret }}' | jq '.user'
        echo "Manually parsed TTL_IN_MINUTES:" 
        echo '${{ steps.fetch-secrets.outputs.my_dynamic_secret }}' | jq '.ttl_in_minutes'
        echo "Manually parsed PASSWORD:"
        echo '${{ steps.fetch-secrets.outputs.my_dynamic_secret }}' | jq '.password'


    - name: Verify Environment Variables using jq
      run: |
        echo "Your environment secret is ${{ env.my_dynamic_secret }}"
        echo "Manually parsed ID:"
        echo '${{ env.my_dynamic_secret }}' | jq '.id'
        echo "Manually parsed USER:"
        echo '${{ env.my_dynamic_secret }}' | jq '.user'
        echo "Manually parsed TTL_IN_MINUTES:"
        echo '${{ env.my_dynamic_secret }}' | jq '.ttl_in_minutes'
        echo "Manually parsed PASSWORD:"
        echo '${{ env.my_dynamic_secret }}' | jq '.password'


    - name: EXTRA 1 - Export Secrets to Environment using jq
      run: |
        echo '${{ steps.fetch-secrets.outputs.my_dynamic_secret }}' | jq -r 'to_entries|map("AKEYLESS_\(.key)=\(.value|tostring)")|.[]' >> $GITHUB_ENV
        
    - name: EXTRA 2 - Verify Exported Variables
      run: |
        echo "AKEYLESS_id = ${{ env.AKEYLESS_id }}"
        echo "AKEYLESS_user = ${{ env.AKEYLESS_user }}"
        echo "AKEYLESS_password = ${{ env.AKEYLESS_password }}"
        echo "AKEYLESS_ttl_in_minutes = ${{ env.AKEYLESS_ttl_in_minutes }}"