---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: app
spec: {}
status: {}

---

apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: akey
spec: {}
status: {}
