apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      checksum/config: 3f91d315b7b454498096090e68270846700adf83463347dd514188706fc2446f
    creationTimestamp: "2023-12-23T16:23:06Z"
    generateName: aks-akeyless-secrets-injection-9fb9d67b7-
    labels:
      app: akeyless-secrets-injection
      pod-template-hash: 9fb9d67b7
      release: aks
    name: aks-akeyless-secrets-injection-9fb9d67b7-8dwzb
    namespace: akeyless
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: aks-akeyless-secrets-injection-9fb9d67b7
      uid: 79bc7490-ebde-4911-9fd7-57b5d5ba87bf
    resourceVersion: "67547"
    uid: 354dad58-b670-4460-b2c7-a2f204542446
  spec:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app: akeyless-secrets-injection
                release: aks
            topologyKey: kubernetes.io/hostname
          weight: 100
    containers:
    - env:
      - name: TLS_CERT_FILE
        value: /var/serving-cert/servingCert
      - name: TLS_PRIVATE_KEY_FILE
        value: /var/serving-cert/servingKey
      - name: INTERNAL_PORT
        value: "8443"
      - name: DEBUG
        value: "false"
      - name: AKEYLESS_AGENT_IMAGE
        value: docker.registry-2.akeyless.io/k8s-secrets-sidecar:0.22.0
      - name: AKEYLESS_ACCESS_ID
        value: p-8mo8oxm1btaykm
      - name: AKEYLESS_ACCESS_TYPE
        value: k8s
      - name: AKEYLESS_AGENT_LIMITS_CPU
        value: 500m
      - name: AKEYLESS_AGENT_LIMITS_MEM
        value: 128Mi
      - name: AKEYLESS_AGENT_REQUESTS_CPU
        value: 250m
      - name: AKEYLESS_AGENT_REQUESTS_MEM
        value: 64Mi
      - name: AKEYLESS_API_GW_URL
        value: https://54.219.122.226.nip.io:8088
      - name: AKEYLESS_K8S_AUTH_CONF_NAME
        value: k8s-conf
      - name: AKEYLESS_URL
        value: https://vault.akeyless.io
      image: docker.registry-2.akeyless.io/k8s-webhook-server:0.22.0
      imagePullPolicy: IfNotPresent
      name: akeyless-secrets-injection
      ports:
      - containerPort: 8443
        protocol: TCP
      resources:
        limits:
          cpu: 500m
          memory: 192Mi
        requests:
          cpu: 250m
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 65534
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/serving-cert
        name: serving-cert
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-wwxrr
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: ip-192-168-117-121.us-west-1.compute.internal
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: aks-akeyless-secrets-injection
    serviceAccountName: aks-akeyless-secrets-injection
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: serving-cert
      secret:
        defaultMode: 420
        secretName: aks-akeyless-secrets-injection
    - name: kube-api-access-wwxrr
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2023-12-23T16:23:06Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2023-12-23T16:23:10Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2023-12-23T16:23:10Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2023-12-23T16:23:06Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://50aafab33508818c7e6ebffd1022fe79f8098d8edf4226432bd6ad054235fe8d
      image: docker.registry-2.akeyless.io/k8s-webhook-server:0.22.0
      imageID: docker.registry-2.akeyless.io/k8s-webhook-server@sha256:b7cb04991ee3e421621552ff88161c5492dc34740ae014b2a28655d142ed2c14
      lastState: {}
      name: akeyless-secrets-injection
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2023-12-23T16:23:10Z"
    hostIP: 192.168.117.121
    phase: Running
    podIP: 192.168.98.233
    podIPs:
    - ip: 192.168.98.233
    qosClass: Burstable
    startTime: "2023-12-23T16:23:06Z"
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      checksum/config: 3f91d315b7b454498096090e68270846700adf83463347dd514188706fc2446f
    creationTimestamp: "2023-12-23T16:23:06Z"
    generateName: aks-akeyless-secrets-injection-9fb9d67b7-
    labels:
      app: akeyless-secrets-injection
      pod-template-hash: 9fb9d67b7
      release: aks
    name: aks-akeyless-secrets-injection-9fb9d67b7-tspj9
    namespace: akeyless
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: aks-akeyless-secrets-injection-9fb9d67b7
      uid: 79bc7490-ebde-4911-9fd7-57b5d5ba87bf
    resourceVersion: "67552"
    uid: 53d71d78-16a1-4916-a9bd-7962f412f8f2
  spec:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app: akeyless-secrets-injection
                release: aks
            topologyKey: kubernetes.io/hostname
          weight: 100
    containers:
    - env:
      - name: TLS_CERT_FILE
        value: /var/serving-cert/servingCert
      - name: TLS_PRIVATE_KEY_FILE
        value: /var/serving-cert/servingKey
      - name: INTERNAL_PORT
        value: "8443"
      - name: DEBUG
        value: "false"
      - name: AKEYLESS_AGENT_IMAGE
        value: docker.registry-2.akeyless.io/k8s-secrets-sidecar:0.22.0
      - name: AKEYLESS_ACCESS_ID
        value: p-8mo8oxm1btaykm
      - name: AKEYLESS_ACCESS_TYPE
        value: k8s
      - name: AKEYLESS_AGENT_LIMITS_CPU
        value: 500m
      - name: AKEYLESS_AGENT_LIMITS_MEM
        value: 128Mi
      - name: AKEYLESS_AGENT_REQUESTS_CPU
        value: 250m
      - name: AKEYLESS_AGENT_REQUESTS_MEM
        value: 64Mi
      - name: AKEYLESS_API_GW_URL
        value: https://54.219.122.226.nip.io:8088
      - name: AKEYLESS_K8S_AUTH_CONF_NAME
        value: k8s-conf
      - name: AKEYLESS_URL
        value: https://vault.akeyless.io
      image: docker.registry-2.akeyless.io/k8s-webhook-server:0.22.0
      imagePullPolicy: IfNotPresent
      name: akeyless-secrets-injection
      ports:
      - containerPort: 8443
        protocol: TCP
      resources:
        limits:
          cpu: 500m
          memory: 192Mi
        requests:
          cpu: 250m
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 65534
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/serving-cert
        name: serving-cert
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-bdlv4
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: ip-192-168-3-230.us-west-1.compute.internal
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: aks-akeyless-secrets-injection
    serviceAccountName: aks-akeyless-secrets-injection
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: serving-cert
      secret:
        defaultMode: 420
        secretName: aks-akeyless-secrets-injection
    - name: kube-api-access-bdlv4
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2023-12-23T16:23:06Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2023-12-23T16:23:10Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2023-12-23T16:23:10Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2023-12-23T16:23:06Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://0417e7363eb6d65d51af2760d746bbe9ad0c8994748a58d8003b3e37acb37bb8
      image: docker.registry-2.akeyless.io/k8s-webhook-server:0.22.0
      imageID: docker.registry-2.akeyless.io/k8s-webhook-server@sha256:b7cb04991ee3e421621552ff88161c5492dc34740ae014b2a28655d142ed2c14
      lastState: {}
      name: akeyless-secrets-injection
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2023-12-23T16:23:09Z"
    hostIP: 192.168.3.230
    phase: Running
    podIP: 192.168.23.16
    podIPs:
    - ip: 192.168.23.16
    qosClass: Burstable
    startTime: "2023-12-23T16:23:06Z"
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: aks
      meta.helm.sh/release-namespace: akeyless
    creationTimestamp: "2023-12-23T16:23:06Z"
    labels:
      app: aks-akeyless-secrets-injection
      app.kubernetes.io/managed-by: Helm
      chart: akeyless-secrets-injection-1.3.4
      component: mutating-webhook
      heritage: Helm
      release: aks
    name: aks-akeyless-secrets-injection
    namespace: akeyless
    resourceVersion: "67503"
    uid: 341c66d4-0eeb-4acb-a19c-c4b87fed3772
  spec:
    clusterIP: 10.100.204.172
    clusterIPs:
    - 10.100.204.172
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: secrets-webhook
      port: 443
      protocol: TCP
      targetPort: 8443
    selector:
      app: akeyless-secrets-injection
      release: aks
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      meta.helm.sh/release-name: aks
      meta.helm.sh/release-namespace: akeyless
    creationTimestamp: "2023-12-23T16:23:06Z"
    generation: 1
    labels:
      app: akeyless-secrets-injection
      app.kubernetes.io/managed-by: Helm
      chart: akeyless-secrets-injection-1.3.4
      component: mutating-webhook
      heritage: Helm
      release: aks
    name: aks-akeyless-secrets-injection
    namespace: akeyless
    resourceVersion: "67556"
    uid: 3b68c27d-f387-453e-93b5-b110b9d621af
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: akeyless-secrets-injection
        release: aks
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          checksum/config: 3f91d315b7b454498096090e68270846700adf83463347dd514188706fc2446f
        creationTimestamp: null
        labels:
          app: akeyless-secrets-injection
          release: aks
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: akeyless-secrets-injection
                    release: aks
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - env:
          - name: TLS_CERT_FILE
            value: /var/serving-cert/servingCert
          - name: TLS_PRIVATE_KEY_FILE
            value: /var/serving-cert/servingKey
          - name: INTERNAL_PORT
            value: "8443"
          - name: DEBUG
            value: "false"
          - name: AKEYLESS_AGENT_IMAGE
            value: docker.registry-2.akeyless.io/k8s-secrets-sidecar:0.22.0
          - name: AKEYLESS_ACCESS_ID
            value: p-8mo8oxm1btaykm
          - name: AKEYLESS_ACCESS_TYPE
            value: k8s
          - name: AKEYLESS_AGENT_LIMITS_CPU
            value: 500m
          - name: AKEYLESS_AGENT_LIMITS_MEM
            value: 128Mi
          - name: AKEYLESS_AGENT_REQUESTS_CPU
            value: 250m
          - name: AKEYLESS_AGENT_REQUESTS_MEM
            value: 64Mi
          - name: AKEYLESS_API_GW_URL
            value: https://54.219.122.226.nip.io:8088
          - name: AKEYLESS_K8S_AUTH_CONF_NAME
            value: k8s-conf
          - name: AKEYLESS_URL
            value: https://vault.akeyless.io
          image: docker.registry-2.akeyless.io/k8s-webhook-server:0.22.0
          imagePullPolicy: IfNotPresent
          name: akeyless-secrets-injection
          ports:
          - containerPort: 8443
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 192Mi
            requests:
              cpu: 250m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 65534
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/serving-cert
            name: serving-cert
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: aks-akeyless-secrets-injection
        serviceAccountName: aks-akeyless-secrets-injection
        terminationGracePeriodSeconds: 30
        volumes:
        - name: serving-cert
          secret:
            defaultMode: 420
            secretName: aks-akeyless-secrets-injection
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2023-12-23T16:23:10Z"
      lastUpdateTime: "2023-12-23T16:23:10Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2023-12-23T16:23:06Z"
      lastUpdateTime: "2023-12-23T16:23:10Z"
      message: ReplicaSet "aks-akeyless-secrets-injection-9fb9d67b7" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "2"
      deployment.kubernetes.io/max-replicas: "3"
      deployment.kubernetes.io/revision: "1"
      meta.helm.sh/release-name: aks
      meta.helm.sh/release-namespace: akeyless
    creationTimestamp: "2023-12-23T16:23:06Z"
    generation: 1
    labels:
      app: akeyless-secrets-injection
      pod-template-hash: 9fb9d67b7
      release: aks
    name: aks-akeyless-secrets-injection-9fb9d67b7
    namespace: akeyless
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: aks-akeyless-secrets-injection
      uid: 3b68c27d-f387-453e-93b5-b110b9d621af
    resourceVersion: "67555"
    uid: 79bc7490-ebde-4911-9fd7-57b5d5ba87bf
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: akeyless-secrets-injection
        pod-template-hash: 9fb9d67b7
        release: aks
    template:
      metadata:
        annotations:
          checksum/config: 3f91d315b7b454498096090e68270846700adf83463347dd514188706fc2446f
        creationTimestamp: null
        labels:
          app: akeyless-secrets-injection
          pod-template-hash: 9fb9d67b7
          release: aks
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: akeyless-secrets-injection
                    release: aks
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - env:
          - name: TLS_CERT_FILE
            value: /var/serving-cert/servingCert
          - name: TLS_PRIVATE_KEY_FILE
            value: /var/serving-cert/servingKey
          - name: INTERNAL_PORT
            value: "8443"
          - name: DEBUG
            value: "false"
          - name: AKEYLESS_AGENT_IMAGE
            value: docker.registry-2.akeyless.io/k8s-secrets-sidecar:0.22.0
          - name: AKEYLESS_ACCESS_ID
            value: p-8mo8oxm1btaykm
          - name: AKEYLESS_ACCESS_TYPE
            value: k8s
          - name: AKEYLESS_AGENT_LIMITS_CPU
            value: 500m
          - name: AKEYLESS_AGENT_LIMITS_MEM
            value: 128Mi
          - name: AKEYLESS_AGENT_REQUESTS_CPU
            value: 250m
          - name: AKEYLESS_AGENT_REQUESTS_MEM
            value: 64Mi
          - name: AKEYLESS_API_GW_URL
            value: https://54.219.122.226.nip.io:8088
          - name: AKEYLESS_K8S_AUTH_CONF_NAME
            value: k8s-conf
          - name: AKEYLESS_URL
            value: https://vault.akeyless.io
          image: docker.registry-2.akeyless.io/k8s-webhook-server:0.22.0
          imagePullPolicy: IfNotPresent
          name: akeyless-secrets-injection
          ports:
          - containerPort: 8443
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 192Mi
            requests:
              cpu: 250m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 65534
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/serving-cert
            name: serving-cert
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: aks-akeyless-secrets-injection
        serviceAccountName: aks-akeyless-secrets-injection
        terminationGracePeriodSeconds: 30
        volumes:
        - name: serving-cert
          secret:
            defaultMode: 420
            secretName: aks-akeyless-secrets-injection
  status:
    availableReplicas: 2
    fullyLabeledReplicas: 2
    observedGeneration: 1
    readyReplicas: 2
    replicas: 2
kind: List
metadata:
  resourceVersion: ""
