apiVersion: v1
kind: Pod
metadata:
  name: mypod2
  namespace: akey
  annotations:
        akeyless/enabled: "true"

spec:
  containers:
  - name: mypod2
    image: alpine
    command:
      - "sh"
      - "-c"
      - "echo $MY_SECRET && echo going to sleep... && sleep 10000"
    env:
    - name: MY_SECRET
      value: akeyless:/dev/projects/test-aky/MySod1

    imagePullPolicy: IfNotPresent
  restartPolicy: Always
